# Generated by Django 5.2 on 2025-04-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='txt',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
