# Generated by Django 5.2 on 2025-05-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accaunts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
